services:
  postgre:
    image: postgres:15.3-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_USER: ${PG_USERNAME}
      POSTGRES_DB: ${PG_DBNAME}
      TZ: Asia/Jakarta
    container_name: postgre
    volumes:
      - pgdata:/var/lib/postgresql/data      
    ports:
      - "5432:5432"
    networks:
      -  sysbit
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready -U $${PG_USERNAME} -d $${PG_NAME} || exit 1"]
    #   interval: 5s
    tty: true