CREATE TABLE IF NOT EXISTS lesson_assets (
	asset_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    lesson_id INTEGER NOT NULL,
	page_id INTEGER NOT NULL,
    step INTEGER NOT NULL,
    type VARCHAR NOT NULL,
    url TEXT NOT NULL
);

ALTER TABLE lesson_assets
ADD CONSTRAINT lesson_page_step_type_unique UNIQUE (lesson_id,page_id,step,type);