CREATE TABLE IF NOT EXISTS lesson_video (
	video_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    lesson_id INTEGER NOT NULL,
    type VARCHAR NOT NULL,
    url TEXT NOT NULL
);
ALTER TABLE lesson_video
ADD CONSTRAINT lesson_type_unique UNIQUE (lesson_id,type);