CREATE TABLE IF NOT EXISTS lesson_page (
	page_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	lesson_id INTEGER NOT NULL,
    page INTEGER NOT NULL
);

ALTER TABLE lesson_page
ADD CONSTRAINT lesson_id_page_unique UNIQUE (lesson_id,page);